### PR TITLE
Fix loki datasource

### PR DESCRIPTION
**Pull request by negbie**

### CODE REVIEW

**Comment by lmangani** [comment]
@negbie the new docker bundle doesn't seem to produce inserts in either prometheus or loki, need to recheck it fresh tomorrow

**Comment by negbie** [comment]
Do you see the some docker output for heplify-server config?

heplify-server    | 2018/12/14 21:18:44.375412 server.go:151: INFO start heplify-server 0.98 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, MQDriver:"", MQAddr:"", MQTopic:"", LokiURL:"http://loki:3100/api/prom/push", LokiBulk:1000, LokiTimer:2, PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", HoraclifixStats:false, RTPAgentStats:false, DBShema:"none", DBDriver:"mysql", DBAddr:"localhost:3306", DBUser:"root", DBPass:"", DBDataTable:"homer_data", DBConfTable:"homer_configuration", DBTableSpace:"", DBBulk:200, DBTimer:2, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartSip:"1h", DBPartQos:"6h", DBDropDays:14, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), LogDbg:"", LogLvl:"info", LogStd:true, Config:"./heplify-server.toml", Version:false}

**Comment by negbie** [comment]
I tested it and it worked. Mby you still have a wrong LokiURL?

**Comment by lmangani** [comment]
just noticed my containers starts with no settings at all apparently...
```
2018/12/14 23:42:46.316654 server.go:151: INFO start heplify-server 0.98 with config.HeplifyServer{HEPAddr:"", HEPTCPAddr:"", HEPTLSAddr:"", ESAddr:"", ESDiscovery:false, MQDriver:"", MQAddr:"", MQTopic:"", LokiURL:"", LokiBulk:0, LokiTimer:0, PromAddr:"", PromTargetIP:"", PromTargetName:"", HoraclifixStats:false, RTPAgentStats:false, DBShema:"", DBDriver:"", DBAddr:"", DBUser:"", DBPass:"", DBDataTable:"", DBConfTable:"", DBTableSpace:"", DBBulk:0, DBTimer:0, DBBuffer:0, DBWorker:0, DBRotate:false, DBPartLog:"", DBPartSip:"", DBPartQos:"", DBDropDays:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string(nil), AlegIDs:[]string(nil), LogDbg:"", LogLvl:"", LogStd:false, Config:"", Version:false}
```

**Comment by negbie** [comment]
docker-compose pull && docker-compose up 
should fix it ;)

**Comment by negbie** [comment]
Wait no settings? Thats strange.

**Comment by negbie** [comment]
Can't reproduce :(

**Comment by lmangani** [comment]
Just running the new compose (w/ your patches) from the homer7-docker repo as is.... testing on a new system to confirm

**Comment by negbie** [comment]
Let me clone it again..

**Comment by negbie** [comment]
Just in case:

docker version
Client:
 Version:           18.09.0-ce
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        4d60db472b
 Built:             Fri Nov  9 00:05:34 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       4d60db472b
  Built:            Fri Nov  9 00:05:11 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by lmangani** [comment]
I think you're using a local build because apparently it was a bad apple pushed to dockerhub... after a clean rebuild now config works with `sipcapture/heplify-server:master` will update `latest` too

**Comment by lmangani** [comment]
Prometheus works but Loki is getting no indices, but I think I'll solve this one out next ;)

**Comment by negbie** [comment]
Take a look at the datasource

**Comment by negbie** [comment]
The autoprovisioning for loki needs more love I think

**Comment by negbie** [comment]
Wait it seems latest loki master broke something...

**Comment by lmangani** [comment]
Loki seems up, but I get labels from promtail but nothing from heplify-server

**Comment by negbie** [comment]
Just pulled the latest heplify-server image and now I don't see any labels too.

**Comment by negbie** [comment]
I triggered a new build for latest

**Comment by lmangani** [comment]
Yeah, definitely something is odd... also, restarting the compose bundle breaks loki everytime (no labels) so we probably need to lock its storage or whatnot, too

**Comment by negbie** [comment]
Ok test with latest heplify-server image. Next build it with tag 0.99

**Comment by negbie** [comment]
I had to fix the datasource again but with latest labels show up.

**Comment by negbie** [comment]
Build 0.99 is up. Lets use it:
image: sipcapture/heplify-server:0.99

**Comment by negbie** [comment]
Tested with 0.99 and all seems fine despite the recreation of the datasource.

**Comment by lmangani** [comment]
What's the issue with the datasource? the provisioning should delete/recreate both right?

image

**Comment by negbie** [comment]
Or mby something with the local yml file. Can't tell now to tired ;) Going to bed now.

**Pull request merged**
